version: "3"
services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - DD_ENV=development
      - DD_SERVICE=pollutrack-api
      - DD_VERSION=1.0
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://datadog-agent:4318
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://datadog-agent:4318/v1/traces
      - DD_SITE=us5.datadoghq.com
    depends_on:
      - datadog-agent

  datadog-agent:
    image: "gcr.io/datadoghq/agent:latest"
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=us5.datadoghq.com
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=0.0.0.0:4318
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
    ports:
      - "8126:8126"
      - "4318:4318"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

  locust:
    build: ./locust
    ports:
      - "8089:8089"
    depends_on:
      - api
