apiVersion: v1
kind: Service
metadata:
  name: pollutrack-api
spec:
  selector:
    app: pollutrack-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: pollutrack-locust
spec:
  selector:
    app: pollutrack-locust
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: NodePort
